apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_PASSWORD
          value: "yourpassword"
        - name: POSTGRES_DB
          value: "storage"
        volumeMounts:
        - name: certs
          mountPath: /certs
        - name: config
          mountPath: /etc/postgresql
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      volumes:
      - name: certs
        hostPath:
          path: /home/salithekid/Desktop/Projeto3Cadeiras/certs
      - name: config
        configMap:
          name: postgres-config
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgresql.conf: |
    ssl = on
    ssl_cert_file = '/certs/example.local.crt'
    ssl_key_file = '/certs/example.local.key'
    ssl_ca_file = '/certs/ca.crt'
    ssl_min_protocol_version = 'TLSv1.3'